# Your project's server will run on localhost:xxxx at this port
PORT: 8000

# Autoprefixer will make sure your CSS works with these browsers
COMPATIBILITY:
  - "last 2 versions"
  - "ie >= 9"
  - "ios >= 7"

# UnCSS will use these settings
UNCSS_OPTIONS:
  html:
    - "src/**/*.html"
  ignore:
    # - !!js/regexp .foundation-mq
    - !!js/regexp ^\.is-.*

# Gulp will reference these paths when it copies files
PATHS:
  # Path to dist folder
  dist: "html"  
  # Paths to static assets that aren't images, CSS, or JavaScript
  assets:
    - "src/assets/**/*"
    - "!src/assets/{img,js,scss}/**/*"
    - "node_modules/normalize.css/normalize.css"
  # Paths to Sass libraries, which can then be loaded with @import
  sass:
    
  # Paths to JavaScript libraries, which are combined into one file
  javascript:
    # Libraries required by Foundation
    - "bower_components/jquery/dist/jquery.js"
    - "bower_components/what-input/dist/what-input.js"
    # Paths to your own project code are here
    - "src/assets/js/!(app).js"
    - "src/assets/js/app.js"

  # Paths to Documentation
  docs:
    - "Documentation/**/*"
  # Paths to JS which shouldn;t be compiled into app.js
  js:
    - "src/assets/js/**/*"
  fonts:
    - "src/assets/fonts/**/*"
  include:
    - "src/assets/include/**/*"
